import evidenceFront from "@/assets/evidence-front.jpg";
import evidenceLabel from "@/assets/evidence-label.jpg";
import type {
  DashboardStats,
  Declaration,
  Evidence,
  Inspection,
  Product,
  ProductImage,
  User,
  Violation,
} from "@/types";

/**
 * Mock fixtures only. No business logic lives here and none of these values
 * represent a real legal determination.
 */

export const MOCK_DISCLAIMER =
  "Demonstration data. Results are illustrative only and are not a legal determination of compliance.";

export const currentUser: User = {
  id: "usr-1",
  name: "A. Rao",
  email: "a.rao@legalmetrology.gov.in",
  designation: "Senior Inspector",
  zone: "Zone 4",
  employeeId: "LM-4417",
  phone: "+91 98••• ••412",
  initials: "AR",
};

export const inspectors = ["A. Rao", "S. Iyer", "P. Nair", "M. Bose"];
export const categories = ["Spices", "Packaged food", "Dairy", "Beverages", "Personal care"];
export const manufacturers = [
  "Kaveri Foods Pvt. Ltd.",
  "Madras Grain Traders",
  "Nilgiri Spice Mills",
  "Coimbatore Dairy Ltd.",
  "Konkan Beverages",
];

export const productImages: ProductImage[] = [
  {
    id: "img-1",
    kind: "front",
    label: "Front of pack",
    url: evidenceFront,
    fileName: "front-of-pack.jpg",
    sizeKb: 412,
    uploadedAt: "2026-08-28T09:12:00Z",
    progress: 100,
    status: "uploaded",
  },
  {
    id: "img-2",
    kind: "label",
    label: "Declaration label",
    url: evidenceLabel,
    fileName: "declaration-label.jpg",
    sizeKb: 388,
    uploadedAt: "2026-08-28T09:13:00Z",
    progress: 100,
    status: "uploaded",
  },
  {
    id: "img-3",
    kind: "mrp",
    label: "MRP area",
    url: evidenceLabel,
    fileName: "mrp-area.jpg",
    sizeKb: 274,
    uploadedAt: "2026-08-28T09:14:00Z",
    progress: 100,
    status: "uploaded",
  },
  {
    id: "img-4",
    kind: "back",
    label: "Back of pack",
    url: evidenceLabel,
    fileName: "back-of-pack.jpg",
    sizeKb: 301,
    uploadedAt: "2026-08-28T09:15:00Z",
    progress: 100,
    status: "uploaded",
  },
];

export const products: Product[] = [
  {
    id: "prd-1",
    name: "Turmeric Powder 200 g",
    brand: "Kaveri Select",
    category: "Spices",
    manufacturer: "Kaveri Foods Pvt. Ltd.",
    manufacturerAddress: "Plot 14, Hosur Industrial Estate, Krishnagiri 635109",
    batchNumber: "KV-2216",
    imageUrl: evidenceFront,
    lastInspectedAt: "2026-08-28",
    complianceStatus: "non_compliant",
    violationCount: 3,
    inspectionIds: ["ins-8842"],
  },
  {
    id: "prd-2",
    name: "Sona Masuri Rice 5 kg",
    brand: "Madras Harvest",
    category: "Packaged food",
    manufacturer: "Madras Grain Traders",
    manufacturerAddress: "22 Mount Road, Chennai 600002",
    batchNumber: "MG-5510",
    imageUrl: evidenceLabel,
    lastInspectedAt: "2026-08-27",
    complianceStatus: "compliant",
    violationCount: 0,
    inspectionIds: ["ins-8839"],
  },
  {
    id: "prd-3",
    name: "Garam Masala 100 g",
    brand: "Nilgiri Gold",
    category: "Spices",
    manufacturer: "Nilgiri Spice Mills",
    manufacturerAddress: "Factory Road, Coonoor 643102",
    batchNumber: "NS-1181",
    imageUrl: evidenceFront,
    lastInspectedAt: "2026-08-27",
    complianceStatus: "manual_review",
    violationCount: 1,
    inspectionIds: ["ins-8835"],
  },
  {
    id: "prd-4",
    name: "Toned Milk 500 ml",
    brand: "Coimbatore Fresh",
    category: "Dairy",
    manufacturer: "Coimbatore Dairy Ltd.",
    manufacturerAddress: "Dairy Complex, Coimbatore 641004",
    batchNumber: "CD-7702",
    imageUrl: evidenceLabel,
    lastInspectedAt: "2026-08-26",
    complianceStatus: "compliant",
    violationCount: 0,
    inspectionIds: ["ins-8831"],
  },
  {
    id: "prd-5",
    name: "Coconut Water 1 L",
    brand: "Konkan Pure",
    category: "Beverages",
    manufacturer: "Konkan Beverages",
    manufacturerAddress: "MIDC Ratnagiri 415639",
    batchNumber: "KB-3308",
    imageUrl: evidenceFront,
    lastInspectedAt: "2026-08-24",
    complianceStatus: "pending",
    violationCount: 0,
    inspectionIds: ["ins-8824"],
  },
  {
    id: "prd-6",
    name: "Herbal Shampoo 180 ml",
    brand: "Vaidya Care",
    category: "Personal care",
    manufacturer: "Kaveri Foods Pvt. Ltd.",
    manufacturerAddress: "Plot 14, Hosur Industrial Estate, Krishnagiri 635109",
    batchNumber: "KV-9004",
    imageUrl: evidenceLabel,
    lastInspectedAt: "2026-08-21",
    complianceStatus: "non_compliant",
    violationCount: 2,
    inspectionIds: ["ins-8817"],
  },
];

function mkInspection(
  id: string,
  reference: string,
  product: Product,
  inspectorName: string,
  createdAt: string,
  status: Inspection["status"],
  score: number,
  violationCount: number,
  highestSeverity: Inspection["highestSeverity"],
  location: string,
): Inspection {
  return {
    id,
    reference,
    productId: product.id,
    productName: product.name,
    brand: product.brand,
    manufacturer: product.manufacturer,
    category: product.category,
    inspectorId: "usr-1",
    inspectorName,
    location,
    createdAt,
    status,
    score,
    violationCount,
    highestSeverity,
    imageIds: ["img-1", "img-2", "img-3", "img-4"],
  };
}

export const inspections: Inspection[] = [
  mkInspection("ins-8842", "INS-2026-08842", products[0], "A. Rao", "2026-08-28", "non_compliant", 72, 3, "critical", "Krishnagiri retail market"),
  mkInspection("ins-8839", "INS-2026-08839", products[1], "S. Iyer", "2026-08-27", "compliant", 96, 0, null, "Chennai wholesale depot"),
  mkInspection("ins-8835", "INS-2026-08835", products[2], "A. Rao", "2026-08-27", "manual_review", 58, 1, "major", "Coonoor mill outlet"),
  mkInspection("ins-8831", "INS-2026-08831", products[3], "P. Nair", "2026-08-26", "compliant", 89, 0, null, "Coimbatore dairy counter"),
  mkInspection("ins-8824", "INS-2026-08824", products[4], "M. Bose", "2026-08-24", "pending", 0, 0, null, "Ratnagiri distributor"),
  mkInspection("ins-8817", "INS-2026-08817", products[5], "S. Iyer", "2026-08-21", "non_compliant", 64, 2, "major", "Hosur retail chain"),
  mkInspection("ins-8809", "INS-2026-08809", products[1], "A. Rao", "2026-08-19", "compliant", 92, 0, null, "Chennai wholesale depot"),
  mkInspection("ins-8802", "INS-2026-08802", products[3], "P. Nair", "2026-08-17", "compliant", 91, 0, null, "Erode dairy outlet"),
  mkInspection("ins-8794", "INS-2026-08794", products[0], "M. Bose", "2026-08-14", "non_compliant", 55, 4, "critical", "Salem retail market"),
  mkInspection("ins-8788", "INS-2026-08788", products[2], "S. Iyer", "2026-08-12", "compliant", 88, 0, null, "Coonoor mill outlet"),
  mkInspection("ins-8779", "INS-2026-08779", products[4], "A. Rao", "2026-08-09", "manual_review", 61, 1, "minor", "Ratnagiri distributor"),
  mkInspection("ins-8771", "INS-2026-08771", products[5], "P. Nair", "2026-08-06", "compliant", 94, 0, null, "Bengaluru retail chain"),
];

export const declarations: Declaration[] = [
  {
    id: "dec-1",
    key: "product_name",
    label: "Product name",
    extractedValue: "Turmeric Powder",
    confidence: 0.97,
    sourceImageId: "img-1",
    sourceImageLabel: "Front of pack",
    status: "pass",
    editable: true,
  },
  {
    id: "dec-2",
    key: "manufacturer_name",
    label: "Manufacturer name",
    extractedValue: "Kaveri Foods Pvt. Ltd.",
    confidence: 0.93,
    sourceImageId: "img-2",
    sourceImageLabel: "Declaration label",
    status: "pass",
    editable: true,
  },
  {
    id: "dec-3",
    key: "manufacturer_address",
    label: "Manufacturer address",
    extractedValue: "Hosur Industrial Estate, Krishnagiri",
    confidence: 0.71,
    sourceImageId: "img-2",
    sourceImageLabel: "Declaration label",
    status: "warning",
    editable: true,
    note: "PIN code not legible in the captured image.",
  },
  {
    id: "dec-4",
    key: "packer_details",
    label: "Packer details",
    extractedValue: "Packed by Kaveri Foods Pvt. Ltd.",
    confidence: 0.88,
    sourceImageId: "img-2",
    sourceImageLabel: "Declaration label",
    status: "pass",
    editable: true,
  },
  {
    id: "dec-5",
    key: "importer_details",
    label: "Importer details",
    extractedValue: null,
    confidence: 0,
    sourceImageId: null,
    sourceImageLabel: null,
    status: "not_detected",
    editable: true,
    note: "Not applicable for domestically manufactured packages.",
  },
  {
    id: "dec-6",
    key: "net_quantity",
    label: "Net quantity",
    extractedValue: "200 g",
    confidence: 0.95,
    sourceImageId: "img-1",
    sourceImageLabel: "Front of pack",
    status: "pass",
    editable: true,
  },
  {
    id: "dec-7",
    key: "mrp",
    label: "Retail sale price (MRP)",
    extractedValue: "Rs. 78",
    confidence: 0.64,
    sourceImageId: "img-3",
    sourceImageLabel: "MRP area",
    status: "fail",
    editable: true,
    note: "Inclusive-of-all-taxes wording not found next to the price.",
  },
  {
    id: "dec-8",
    key: "date_of_packing",
    label: "Month and year of packing",
    extractedValue: null,
    confidence: 0,
    sourceImageId: null,
    sourceImageLabel: null,
    status: "fail",
    editable: true,
    note: "No packing date located on any supplied image.",
  },
  {
    id: "dec-9",
    key: "consumer_care",
    label: "Consumer care details",
    extractedValue: "care@kaverifoods.example · 1800 000 000",
    confidence: 0.82,
    sourceImageId: "img-4",
    sourceImageLabel: "Back of pack",
    status: "pass",
    editable: true,
  },
  {
    id: "dec-10",
    key: "country_of_origin",
    label: "Country of origin",
    extractedValue: "India",
    confidence: 0.9,
    sourceImageId: "img-4",
    sourceImageLabel: "Back of pack",
    status: "pass",
    editable: true,
  },
  {
    id: "dec-11",
    key: "other",
    label: "Unit sale price",
    extractedValue: "Rs. 39 / 100 g",
    confidence: 0.55,
    sourceImageId: "img-3",
    sourceImageLabel: "MRP area",
    status: "manual_review",
    editable: true,
    note: "Low confidence reading — inspector confirmation required.",
  },
];

export const violations: Violation[] = [
  {
    id: "vio-1",
    inspectionId: "ins-8842",
    title: "Month and year of packing not declared",
    description:
      "No date of manufacture, packing or import could be located on the principal display panel or on the declaration label.",
    detectedValue: null,
    expectedRequirement:
      "Month and year in which the commodity was pre-packed must be declared on the package.",
    ruleReference: "Rule 6(1)(d), LM (PC) Rules, 2011",
    severity: "critical",
    category: "Missing declaration",
    evidenceImageId: "img-2",
    imageRegion: { x: 34, y: 52, width: 30, height: 16 },
    recommendation:
      "Direct the packer to print the month and year of packing on the principal display panel before further sale.",
    status: "open",
  },
  {
    id: "vio-2",
    inspectionId: "ins-8842",
    title: "Retail sale price wording incomplete",
    description:
      "Price is printed as 'Rs. 78' without the mandatory 'Maximum retail price ... inclusive of all taxes' wording.",
    detectedValue: "Rs. 78",
    expectedRequirement:
      "Retail sale price must be declared as 'Maximum retail price Rs. ... inclusive of all taxes'.",
    ruleReference: "Rule 6(1)(e), LM (PC) Rules, 2011",
    severity: "major",
    category: "Price declaration",
    evidenceImageId: "img-3",
    imageRegion: { x: 52, y: 60, width: 26, height: 12 },
    recommendation: "Reprint the price panel with the full prescribed wording.",
    status: "open",
  },
  {
    id: "vio-3",
    inspectionId: "ins-8842",
    title: "Manufacturer address incomplete",
    description:
      "The complete address including PIN code is not legible on the declaration label.",
    detectedValue: "Hosur Industrial Estate, Krishnagiri",
    expectedRequirement:
      "Name and complete address of the manufacturer or packer must be declared.",
    ruleReference: "Rule 6(1)(a), LM (PC) Rules, 2011",
    severity: "minor",
    category: "Manufacturer details",
    evidenceImageId: "img-2",
    imageRegion: { x: 30, y: 34, width: 40, height: 14 },
    recommendation: "Capture a higher resolution label image and re-verify the address block.",
    status: "acknowledged",
  },
  {
    id: "vio-4",
    inspectionId: "ins-8835",
    title: "Net quantity font height below prescribed size",
    description: "Declared net quantity appears smaller than the prescribed minimum height.",
    detectedValue: "100 g",
    expectedRequirement: "Minimum height of numerals as prescribed for the pack area.",
    ruleReference: "Rule 9(2), LM (PC) Rules, 2011",
    severity: "major",
    category: "Labeling / pack",
    evidenceImageId: "img-1",
    recommendation: "Measure the printed numerals on site and record the finding.",
    status: "open",
  },
  {
    id: "vio-5",
    inspectionId: "ins-8817",
    title: "Consumer care details missing",
    description: "No consumer care contact number or email is declared on the package.",
    detectedValue: null,
    expectedRequirement: "Consumer care contact details must be declared on the package.",
    ruleReference: "Rule 6(1)(f), LM (PC) Rules, 2011",
    severity: "major",
    category: "Missing declaration",
    evidenceImageId: "img-4",
    recommendation: "Issue notice to the packer to add consumer care details.",
    status: "open",
  },
];

export const evidenceItems: Evidence[] = [
  {
    id: "ev-1",
    inspectionId: "ins-8842",
    imageId: "img-1",
    imageUrl: evidenceFront,
    caption: "Front of pack — principal display panel",
    capturedAt: "2026-08-28T09:12:00Z",
    kind: "front",
    linkedViolationIds: [],
  },
  {
    id: "ev-2",
    inspectionId: "ins-8842",
    imageId: "img-2",
    imageUrl: evidenceLabel,
    caption: "Declaration label — address and packing date area",
    capturedAt: "2026-08-28T09:13:00Z",
    kind: "label",
    linkedViolationIds: ["vio-1", "vio-3"],
  },
  {
    id: "ev-3",
    inspectionId: "ins-8842",
    imageId: "img-3",
    imageUrl: evidenceLabel,
    caption: "MRP area close-up",
    capturedAt: "2026-08-28T09:14:00Z",
    kind: "mrp",
    linkedViolationIds: ["vio-2"],
  },
  {
    id: "ev-4",
    inspectionId: "ins-8842",
    imageId: "img-4",
    imageUrl: evidenceLabel,
    caption: "Back of pack — consumer care block",
    capturedAt: "2026-08-28T09:15:00Z",
    kind: "back",
    linkedViolationIds: [],
  },
];

export const dashboardStats: DashboardStats = {
  totalInspections: 1284,
  productsScanned: 1512,
  compliant: 742,
  nonCompliant: 542,
  pending: 61,
  compliancePercentage: 57.8,
  monthlyTrend: [
    { month: "Mar", inspections: 312, violations: 118 },
    { month: "Apr", inspections: 254, violations: 96 },
    { month: "May", inspections: 348, violations: 141 },
    { month: "Jun", inspections: 216, violations: 74 },
    { month: "Jul", inspections: 285, violations: 103 },
    { month: "Aug", inspections: 191, violations: 68 },
  ],
  violationCategories: [
    { category: "Missing declaration", count: 186 },
    { category: "Labeling / pack", count: 142 },
    { category: "Price declaration", count: 98 },
    { category: "Manufacturer details", count: 71 },
  ],
  severityBreakdown: [
    { severity: "critical", count: 96 },
    { severity: "major", count: 214 },
    { severity: "minor", count: 187 },
  ],
};

export const reportRecommendations = [
  "Issue a compliance notice to the packer for the missing month and year of packing.",
  "Require reprinting of the retail sale price panel with the prescribed wording.",
  "Re-inspect the batch after 30 days and record corrective action taken.",
];
